queue_rules:
  - name: default
    queue_conditions:
      - base=main
      - label~=merge-queue|dependencies
    merge_conditions:
      - check-success=buildbot/nix-build
    merge_method: rebase
defaults:
  actions:
    queue:
      allow_merging_configuration_change: true

pull_request_rules:
  - name: refactored queue action rule
    conditions: []
    actions:
      queue:
