cut_body_after = "" # don't include text from the PR body in the merge commit message
status = [
  "cross-build",
  "tests (nixpkgs=https://github.com/NixOS/nixpkgs/archive/nixos-22.11.tar.gz, macos-latest)",
  "tests (nixpkgs=https://github.com/NixOS/nixpkgs/archive/nixos-22.11.tar.gz, ubuntu-latest)",
  "tests (nixpkgs=https://github.com/NixOS/nixpkgs/archive/nixpkgs-unstable.tar.gz, macos-latest)",
  "tests (nixpkgs=https://github.com/NixOS/nixpkgs/archive/nixpkgs-unstable.tar.gz, ubuntu-latest)"
]
