name: "Test"
on:
  pull:
    branches: [ "main" ]
  pull_request:
  schedule:
    - cron:  '51 2 * * *'
jobs:
  cross-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v12
    - run: nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/nixpkgs-unstable.tar.gz --pure -p gox -p go --run "gox -osarch '!darwin/386' ."
  tests:
    strategy:
      matrix:
        nixPath:
          - nixpkgs=https://github.com/NixOS/nixpkgs/archive/nixos-20.09.tar.gz
          - nixpkgs=https://github.com/NixOS/nixpkgs/archive/nixpkgs-unstable.tar.gz
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: "${{ matrix.nixPath }}"
    - name: Setup cachix
      uses: cachix/cachix-action@v8
      with:
        name: mic92
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: Build nix packages
      run: nix-build --no-out-link
